# Versuch mit Six-Website

https://www.six-group.com/exchanges/indices/security_info_de.html?id=CH0009987501CHF9

In [21]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
import time
import pandas as pd
from bs4 import BeautifulSoup
import random
import numpy as np
import re
import glob

In [2]:
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from time import sleep
driver = webdriver.Chrome(executable_path='/usr/bin/chromedriver')
driver.get("https://www.six-group.com/exchanges/indices/security_info_de.html?id=CH0009987501CHF9")
sleep(2)
driver.set_window_size(1920, 1016)
driver.find_element(By.ID, "swx_widget__ImageTabButton_2").click()
sleep(2)
driver.find_element_by_id('swx_widget__ImageTabButton_6').click()
sleep(2)
element = driver.find_element(By.ID, "tabs_level2_3_tablist")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
sleep(2)
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
driver.find_element(By.NAME, "actionSUBMIT").click()

csv-datei landet im download-folder, den weg kann ich nicht nachvollziehen

In [28]:
#datei einlesen
#downloadpath = "8888/notebooks/Downloads/info_market_data_download.csv"
#downloadpath = "localhost:8888/tree/Downloads/info_market_data_download.csv"
downloadpath = "/home/pc/Downloads/info_market_data_download.csv"

In [60]:
pd.set_option('display.max_rows', None)
df = pd.read_csv(downloadpath, encoding= 'unicode_escape', skiprows=2, sep=';')


#.astype(float)
#pd.read_csv(..., dtype=str)

In [61]:
df = df.convert_objects(convert_numeric=True)

/home/pc/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.

In [69]:
df.head(5)

                   Date     Price  Volume  Unnamed: 3
0            18.03.2020   9995.45       0         NaN
1            17.03.2020  10296.23       0         NaN
2            16.03.2020  10029.88       0         NaN
3            13.03.2020  10227.06       0         NaN
4            12.03.2020  10144.29       0         NaN

In [70]:
#df['Date'] = pd.to_datetime(df['Date'], format= '%d/%m/%Y')

In [72]:
#df['Date'] = pd.to_datetime(df['Date'].str.strip(), format='%d/%m/%Y')

In [73]:
#df['New Date'] = pd.to_datetime(df['Date'], format="%d.%m.%Y")

In [63]:
df.dtypes

        Date     object
Price           float64
Volume            int64
Unnamed: 3      float64
dtype: object

In [47]:
#df.iloc() = df.iloc().astype(float)

SyntaxError: can't assign to function call (<ipython-input-47-c5e8c27b54d5>, line 1)

df

In [24]:
downloadpath = np.array(downloadpath).astype(np.float)



#data2 = np.array(data).astype(np.float)

ValueError: could not convert string to float: '/home/pc/Downloads/info_market_data_download.csv'

In [ ]:
df

In [9]:
df.dtypes

SPI® TR (SXGE/CH0009987501)    object
dtype: object

In [7]:
df.head(62)

         SPI® TR (SXGE/CH0009987501)
0                        18.03.2020;
1                 Date;Price;Volume;
2              18.03.2020;9995.45;0;
3             17.03.2020;10296.23;0;
4             16.03.2020;10029.88;0;
5             13.03.2020;10227.06;0;
6             12.03.2020;10144.29;0;
7             11.03.2020;11161.17;0;
8             10.03.2020;11227.97;0;
9             09.03.2020;11248.96;0;
10            06.03.2020;11880.22;0;
11            05.03.2020;12347.87;0;
12            04.03.2020;12482.78;0;
13            03.03.2020;12300.34;0;
14            02.03.2020;12046.83;0;
15            28.02.2020;11897.75;0;
16            27.02.2020;12341.04;0;
17            26.02.2020;12703.63;0;
18            25.02.2020;12670.86;0;
19            24.02.2020;12926.59;0;
20            21.02.2020;13400.18;0;
21            20.02.2020;13453.31;0;
22            19.02.2020;13561.17;0;
23            18.02.2020;13424.11;0;
24            17.02.2020;13457.28;0;
25            14.02.2020;13419.95;0;
26            13.02.2020;13356.42;0;
27            12.02.2020;13373.62;0;
28            11.02.2020;13397.54;0;
29            10.02.2020;13331.64;0;
30            07.02.2020;13280.42;0;
31            06.02.2020;13297.95;0;
32            05.02.2020;13284.03;0;
33            04.02.2020;13077.32;0;
34             03.02.2020;12916.3;0;
35            31.01.2020;12870.99;0;
36            30.01.2020;13013.22;0;
37            29.01.2020;13150.38;0;
38             28.01.2020;13055.3;0;
39            27.01.2020;12940.79;0;
40            24.01.2020;13149.91;0;
41            23.01.2020;13104.33;0;
42            22.01.2020;13211.52;0;
43            21.01.2020;13194.07;0;
44            20.01.2020;13134.37;0;
45            17.01.2020;13117.25;0;
46            16.01.2020;12947.78;0;
47            15.01.2020;12914.36;0;
48            14.01.2020;12894.36;0;
49             13.01.2020;12857.7;0;
50             10.01.2020;12866.5;0;
51            09.01.2020;12880.66;0;
52            08.01.2020;12879.51;0;
53            07.01.2020;12924.74;0;
54             06.01.2020;12899.7;0;
55            03.01.2020;12938.67;0;
56             30.12.2019;12837.5;0;
57            27.12.2019;12972.24;0;
58            23.12.2019;12957.44;0;
59            20.12.2019;12895.69;0;
60            19.12.2019;12767.23;0;
61            18.12.2019;12748.55;0;